add LoongArch64 support for grub
loongarch64/grub pull request #1
Opened 2021-05-28 06:32 UTC by zwaizwai

2021-05-28 10:57 UTC, xen0n commented
这个有点长，我需要看3到4天时间，预定一个 review 坑位

2021-06-01 07:59 UTC, yetist commented on grub-core/lib/gnulib-patches/loongarch.patch
> +diff --git a/build-aux/config.guess b/build-aux/config.guess
这个文件方便测试用的，应该在最终提交中去掉。

2021-06-01 07:59 UTC, yetist commented on bootstrap.conf
> +  patch -p1 -i "grub-core/lib/gnulib-patches/loongarch.patch"
只为测试使用，正式提交中应去掉。

2021-06-01 07:59 UTC, yetist commented on grub-core/lib/loongarch64/efi/loongarch64.c
> + *  Copyright (C) 2017 Free Software Foundation, Inc.
新文件，可以写copyright.

2021-06-01 07:59 UTC, yetist commented on include/grub/loongarch64/time.h
> +}
"idle"指令用在这里是不是挺合适？

2021-06-01 07:59 UTC, yetist commented on util/grub-mkimagexx.c
> +	    if (image_target->elf_target == EM_MIPS && image_target->voidp_sizeof == 8)
这里针对EM_MIPS做了特殊处理，如果不处理MIPS的话，是不是就不需要对通用代码做修改了？

2021-06-05 12:10 UTC, hudsonzuo commented on util/grub-mkimagexx.c
> +	    if (image_target->elf_target == EM_MIPS && image_target->voidp_sizeof == 8)
这里的没显示全，容易误解。命令行下面看更清楚。

2021-06-05 12:21 UTC, hudsonzuo commented on util/grub-mkimagexx.c
>        }
translate_relocation_la64 怎么样？

2021-06-29 09:54 UTC, yetist commented
@loongarch64/dev-team 请大家有空review一下grub，谢谢。

2021-07-05 02:19 UTC, zhuyaliang commented on include/grub/loongarch64/memory.h
> +grub_map_memory (grub_phys_addr_t a, grub_size_t size)
多余的参数size ， 可以使用
```
grub_size_t size __attribute__ ((unused))
```

2021-07-05 02:19 UTC, zhuyaliang commented on grub-core/loader/loongarch64/linux.c
> +        grub_dprintf("loongson", "map[%d]:type %x, start 0x%llx, end 0x%llx\n",
打印格式错误
```
format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘grub_uint64_t’
```

2021-07-05 02:19 UTC, zhuyaliang commented on grub-core/loader/loongarch64/linux.c
> +      checksum = grub_efi_loongarch64_grub_calculatechecksum8(new_interface_mem, new_interface_mem->header.length);
类型传递错误，需要强转一下类型
```
‘const grub_uint8_t *’ {aka ‘const unsigned char *’} but argument is of type ‘mem_map *’
```

2021-07-05 02:19 UTC, zhuyaliang commented on grub-core/kern/loongarch64/efi/init.c
> +  grub_install_get_time_ms (grub_efi_get_time_ms);
增加头文件#include <include/grub/time.h>

2021-07-05 02:19 UTC, zhuyaliang commented on grub-core/lib/loongarch64/efi/loongarch64.c
> +static void
这些初始化函数为什么都没有用到？
```
lib/loongarch64/efi/loongarch64.c:135:1: error: ‘grub_efi_loongarch64_init_special_attribute’ defined but not used [-Werror=unused-function]
 grub_efi_loongarch64_init_special_attribute (grub_efi_loongarch64_smbios_table *smbios_table)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/loongarch64/efi/loongarch64.c:122:1: error: ‘grub_efi_loongarch64_init_interface_info’ defined but not used [-Werror=unused-function]
 grub_efi_loongarch64_init_interface_info (grub_efi_loongarch64_smbios_table *smbios_table)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/loongarch64/efi/loongarch64.c:109:1: error: ‘grub_efi_loongarch64_init_irq_src_routing_table’ defined but not used [-Werror=unused-function]
 grub_efi_loongarch64_init_irq_src_routing_table (grub_efi_loongarch64_smbios_table *smbios_table)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/loongarch64/efi/loongarch64.c:96:1: error: ‘grub_efi_loongarch64_init_system_info’ defined but not used [-Werror=unused-function]
 grub_efi_loongarch64_init_system_info (grub_efi_loongarch64_smbios_table *smbios_table)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/loongarch64/efi/loongarch64.c:83:1: error: ‘grub_efi_loongarch64_init_cpu_info’ defined but not used [-Werror=unused-function]
 grub_efi_loongarch64_init_cpu_info (grub_efi_loongarch64_smbios_table *smbios_table)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/loongarch64/efi/loongarch64.c:74:1: error: ‘grub_efi_loongarch64_init_smbios’ defined but not used [-Werror=unused-function]
 grub_efi_loongarch64_init_smbios (grub_efi_loongarch64_smbios_table *smbios_table)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/loongarch64/efi/loongarch64.c:47:1: error: ‘grub_efi_loongarch64_init_reset_system’ defined but not used [-Werror=unused-function]
```

2021-07-05 02:19 UTC, zhuyaliang commented on grub-core/lib/loongarch64/efi/loongarch64.c
> +   grub_dprintf("loongson", "map[%d]:type %x, start 0x%llx, end 0x%llx\n",
打印格式

2021-09-28 06:34 UTC, xen0n requested changes

2021-09-28 06:34 UTC, xen0n commented on grub-core/kern/loongarch64/cache.S
> +	jirl $zero,$ra,0
新的推上游的工具链都支持 `jr $ra`，不用写原始指令了，读起来顺一点

2021-09-28 06:34 UTC, xen0n commented on include/grub/elf.h
> +#define EM_LOONGARCH64	258		/* LoongArch64 architecture */
请跟 binutils 上游保持一致

```suggestion
#define EM_LOONGARCH	258		/* LoongArch */
```

2021-09-28 06:34 UTC, xen0n commented on include/grub/efi/pe32.h
> +#define GRUB_PE32_MACHINE_LOONGARCH64		0x6264
这边的东西跟微软确认过没有？

2021-09-28 06:34 UTC, xen0n commented on grub-core/lib/loongarch64/relocator.c
> +  grub_uint32_t lu52id=0x03000000;
这些东西应该拿 `#define` 定义

2021-09-28 06:34 UTC, xen0n commented on grub-core/lib/loongarch64/relocator.c
> +  grub_uint32_t andi=0x4c000000;
1. 用 `#define`
2. `0x4c000000` 不是 `jirl` 吗？为啥写 `andi`？

2021-09-28 06:34 UTC, xen0n commented on grub-core/lib/loongarch64/efi/loongarch64_asm.S
> +	li.w		$a0, 3
这一片代码肯定没有测试过，怎么还像 MIPS 一样有 delay slot 的用法，参数都有一个在跳转之后才装入

2021-09-28 06:34 UTC, xen0n commented on grub-core/loader/loongarch64/linux.c
> +      //tmp_index = grub_efi_loongson_memmap_sort(acpi_nvs_mem, acpi_nvs_index, new_interface_mem, tmp_index, GRUB_EFI_LOONGSON_ACPI_NVS);
用不着的代码就删掉，不要只是注释

2021-09-28 06:34 UTC, xen0n commented on include/grub/loongarch64/efi/memory.h
> +  asm volatile ("csrrd %0, 0x181" : "=r" (addr));
`0x181` 是魔数，不便维护。建议在外边 `#define`，然后这边用 `"i"(XXX)` 的方式传进来

2021-09-28 06:34 UTC, xen0n commented on include/grub/loongarch64/io.h
> +#define	GRUB_IO_H	1
grub 这边的头文件 include guard 都是这么写的吗？需要那个 `1` 和神奇的 tab 缩进吗？

2021-09-28 06:34 UTC, xen0n commented on include/grub/loongarch64/time.h
> +}
同意，应该看看能不能加个 `idle`

2021-09-28 06:34 UTC, xen0n commented on util/grub-install.c
> +	      efi_file = "grubloongarch64.efi";
这边 UEFI 标准里要求 `grubloongarch64` 还是 `grubla64`？

2021-09-28 06:34 UTC, xen0n commented on util/grub-mkimagexx.c
> +#define RELOC_STACK_MAX 1024
有必要这么大吗？我看实际对 stack machine 的使用，这里深度甚至 16 就够了

2021-09-28 06:34 UTC, xen0n commented on util/grub-mkimagexx.c
> +				break;
这边我看 `grub-core/kern/loongarch64/dl.c` 有一坨几乎完全相同的东西，看看尽量想办法复用一下

2021-09-28 06:34 UTC, xen0n commented on util/grub-mkimagexx.c
> +				oprs[opri]=opr1 - opr2;
手工做栈顶指针调整非常丑陋，比如这里就会出现连续的 `--` 和 `++`，建议是整个块前面 `#define` 两个 helpers，中间都用 helper 实现入栈出栈的操作，结束之后 `#undef` 掉

2021-09-28 06:34 UTC, xen0n commented on util/grub-mkimagexx.c
> +	Elf_Rela *r;
这边是重构了以前已有的代码？建议拆提交。上游不会允许一整个大提交同时做这么多事情

2021-09-28 06:34 UTC, xen0n commented on util/grub-mkimagexx.c
> +	    if (image_target->elf_target == EM_MIPS && image_target->voidp_sizeof == 8)
这边是重构了已有代码，跟上面评论的另一处好像又不是同一个重构动作，总之也要拆提交

2021-09-28 06:54 UTC, xen0n commented on grub-core/lib/loongarch64/efi/loongarch64_asm.S
> +	move		$a3, $zero
这边的 `bl + ra` 是 MIPS 取不到 PC 才玩的花招，LA 不需要这么搞，直接 PC-relative 就能定位到正确位置了：

```asm
reset_system:
        move            $a1, $zero
        move            $a2, $zero
        move            $a3, $zero
        pcaddi          $t8, (%pcrel(grub_efi_loongarch64_reset_system_addr) >> 2)
        jr              $t8
```

2021-09-28 07:56 UTC, xen0n commented on conf/Makefile.common
> +  CPPFLAGS_PLATFORM = -fno-strict-aliasing -march=loongarch -mabi=lp64 -fno-plt -Wa,-mla-global-with-pcrel
`-march=loongarch` 在开源工具链已经不存在了，建议去掉 `-march` 选项

2021-10-06 10:09 UTC, xen0n commented on util/grub-install.c
> +	      efi_file = "BOOTLOONGARCH64.EFI";
目前无论 CLFS 或者 Loongnix 提供的可用系统镜像中，这个文件都叫 `BOOTLOONGARCH.EFI`，可能在 UEFI 上游标准正式添加 LA 支持之前，这边要改成和真机默认行为一样？

2021-10-06 10:10 UTC, xen0n commented on util/grub-install.c
> +	      efi_file = "grubloongarch64.efi";
Never mind，这个文件叫啥都无所谓，有所谓的是前面 `BOOTxxx.EFI` 这个名字

2021-12-20 06:27 UTC, yetist commented on grub-core/lib/loongarch64/efi/loongarch64.c
> + *  Copyright (C) 2017 Free Software Foundation, Inc.
经过了解，GNU FSF 不加自己的 copyright，只加 GNU FSF 的。

2021-12-20 06:31 UTC, yetist commented on grub-core/lib/loongarch64/efi/loongarch64.c
> +static void
这些看起来真的没有使用，我已经删除了。

2021-12-20 06:31 UTC, yetist commented on include/grub/elf.h
> +#define EM_LOONGARCH64	258		/* LoongArch64 architecture */
已处理

2021-12-20 07:06 UTC, yetist commented on include/grub/efi/pe32.h
> +#define GRUB_PE32_MACHINE_LOONGARCH64		0x6264
已经和 PE 文档做了同步。

2021-12-20 07:41 UTC, xen0n commented
commit e8c9f07cff8333955ae6182c84dc901c8051a6c0 这是之前传言了一阵子的删除旧固件兼容性的提交吗？

2021-12-20 07:44 UTC, yetist commented on grub-core/lib/loongarch64/efi/loongarch64_asm.S
> +	move		$a3, $zero
reset 使用 uefi 的 runtime 服务了，此文件被删掉了

2021-12-20 07:53 UTC, yetist commented
> commit e8c9f07cff8333955ae6182c84dc901c8051a6c0 这是之前传言了一阵子的删除旧固件兼容性的提交吗？

没听到传言，很可能是早期使用传参规范中的代码，我看现在没啥用，给清理了，好好帮忙 review 一下，准备往上游推了

2021-12-23 08:02 UTC, xen0n commented on build.sh
> +#sudo apt install ttf-unifont ttf-dejavu libfreetype6-dev efibootmgr
中文啥情况？这文件是预期要向上游提交的吗，我看不像？

2021-12-23 08:04 UTC, xen0n commented on grub-core/kern/loongarch64/dl_helper.c
> +  *place = *place | ((a & 0x1f) << 10);
用 `|=` 下同

```suggestion
  *place |= ((a & 0x1f) << 10);
```

2021-12-23 08:05 UTC, xen0n commented on grub-core/lib/loongarch64/relocator_asm.S
> +	st.d $r11,$r9,0
逗号后边都加空格，所有地方都自查一下

2021-12-23 08:05 UTC, xen0n commented on include/grub/loongarch64/efi/loongarch64.h
> +typedef struct _extention_list_hdr{
extension

2021-12-23 08:06 UTC, xen0n commented on include/grub/loongarch64/linux.h
> + * riscv的version字段在0x20偏移处，现在LoongArch没有使用，是0
中文要翻译

2021-12-23 08:08 UTC, xen0n commented on util/grub-mkimagexx.c
> +		   GRUB_LOONGARCH64_RELOCATION (stack, target, sym_addr);
别的架构类似的写法此处也加分号吗？这个宏的扩展结果是一堆 switch 选择肢，不是表达式也不是语句，按说不应该加分号的。

2021-12-23 10:25 UTC, yetist commented on build.sh
> +#sudo apt install ttf-unifont ttf-dejavu libfreetype6-dev efibootmgr
这个文件不像上游提交。

2021-12-23 10:40 UTC, xen0n commented on build.sh
> +#sudo apt install ttf-unifont ttf-dejavu libfreetype6-dev efibootmgr
那塞个人分支去，这分支/PR 我理解是用来 stage 上游提交内容的。

2021-12-23 11:12 UTC, yetist commented on build.sh
> +#sudo apt install ttf-unifont ttf-dejavu libfreetype6-dev efibootmgr
嗯，最后阶段会处理掉，目前在 rework ，后面还得整个拆commit

2021-12-23 11:16 UTC, xen0n commented on build.sh
> +#sudo apt install ttf-unifont ttf-dejavu libfreetype6-dev efibootmgr
哦，提交会全部重新拆是吧，那这一阵就先不看这PR了哈

2021-12-24 05:10 UTC, yetist commented on include/grub/loongarch64/efi/loongarch64.h
> +typedef struct _extention_list_hdr{
没问题，内核是这样写的: [ arch/loongarch/include/asm/mach-loongson64/boot_param.h](https://github.com/loongson/linux/blob/dbff6e4846e021524294de16b7fa3c3e1c4e1179/arch/loongarch/include/asm/boot_param.h#L31)

2023-05-18 02:11 UTC, xen0n commented
Closing as the port is merged upstream; see #5 #6.

2023-05-18 02:11 UTC, closed without merging